### ISSUE TITLE
Examples don't compile in Xcode 14.0 beta 6 (14A5294g)

### ISSUE THREAD

**Issue by valeriyvan** [kelvin13/jpeg#10]
<unknown>:0: error: conflicting arguments to generic parameter 'Elements' ('[(luminance: (x: Int, y: Int), chrominance: (x: Int, y: Int), name: String)]' vs. '[((Int, Int), (Int, Int), String)]')
*/jpeg/examples/encode-basic/main.swift:30:1: error: conflicting arguments to generic parameter 'Self' ('[(luminance: (x: Int, y: Int), chrominance: (x: Int, y: Int), name: String)]' vs. '[((Int, Int), (Int, Int), String)]')
]
^
*p/jpeg/examples/encode-basic/main.swift:25:1: error: conflicting arguments to generic parameter 'Element' ('(luminance: (x: Int, y: Int), chrominance: (x: Int, y: Int), name: String)' vs. '((Int, Int), (Int, Int), String)')
[
^
*/jpeg/examples/encode-basic/main.swift:25:1: error: conflicting arguments to generic parameter 'Element' ('(luminance: (x: Int, y: Int), chrominance: (x: Int, y: Int), name: String)' vs. '((Int, Int), (Int, Int), String)')
[
^
*/jpeg/examples/encode-basic/main.swift:30:1: error: conflicting arguments to generic parameter 'Self' ('[(luminance: (x: Int, y: Int), chrominance: (x: Int, y: Int), name: String)]' vs. '[((Int, Int), (Int, Int), String)]')
]
^
<unknown>:0: error: conflicting arguments to generic parameter 'Elements' ('[(luminance: (x: Int, y: Int), chrominance: (x: Int, y: Int), name: String)]' vs. '[((Int, Int), (Int, Int), String)]')
