### ISSUE TITLE
Fails to build with Xcode 14.0 beta 6 (14A5294g)

### ISSUE THREAD

**Issue by valeriyvan** [kelvin13/jpeg#6]
/private/tmp/jpeg/sources/jpeg/encode.swift:203:39: error: the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
        let values:[Int16]          = .init(unsafeUninitializedCapacity: count)
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
